server:
  port: 8090

spring.activemq:
  broker-url: failover:(tcp://localhost:61616,tcp://localhost:61615)?randomize=false&reconnectSupported=true&jms.redeliveryPolicy.maximumRedeliveries=0
  user: admin
  password: admin